### ISSUE TITLE
evil-mode可否加入支持?

### ISSUE THREAD

**Issue by jueqingsizhe66** [manateelazycat/lazy-search#1]
emacs配置如果支持evil-mode，那么会和lazy-search的按键冲突(虽然能够激活lazy_search,也能`q`退出，但是单键命令不好使)
虽然知道作者不适用evil-mode，能否在lazy-search加入evil-mode支持？

即： **能否激活lazy-search(M-s)的时候，退出evil-mode(`M-x evil-exit-visual-state`),然后在`q`的时候激活evil-mode(`M-x evil-mode`)? 这样也能让一些使用evil-mode的人能够用得上**。

**Comment by manateelazycat** [comment]
我不用 evil-mode, 不会去花时间研究. 
但是欢迎发送补丁, 我乐于合并相关的补丁.
